repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
      - id: flake8
  -   repo: https://github.com/hcodes/yaspeller
      rev: v7.0.0
      hooks:
      -   id: yaspeller