---
site_name: Azure TRE
site_url: https://github.com/microsoft/AzureTRE
site_description: Azure TRE
site_author: Microsoft

repo_url: https://github.com/microsoft/AzureTre/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: default
    primary: blue grey
    accent: indigo
  logo: assets/ms_icon.png
  favicon: assets/ms_icon.png
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.pathconverter
  - mdx_truly_sane_lists
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Overview: # Pages to explain what the Azure TRE
      - Introducing the AzureTRE: index.md # Introduction to the concept of a TRE, and the AzureTRE
      - User Roles: azure-tre-overview/user-roles.md # The users and roles within an Azure TRE
      - Architecture: # Pages to help understand the components, infra, and networking
          - System Architecture: azure-tre-overview/architecture.md
          - Network Architecture: azure-tre-overview/networking.md
          - Azure Resources: azure-tre-overview/tre-resources-breakdown.md
          - Airlock: azure-tre-overview/airlock.md
          - Cost Reporting: azure-tre-overview/cost-reporting.md
      - Terms and Definitions: using-tre/terms-definitions.md
      #- Compliance: azure-tre-overview/compliance-info.md

  - QuickStart: # Setup steps for anyone performing an initial deployment of the AzureTRE for eval purposes
      - tre-admins/setup-instructions/index.md
      - 1. Prerequisites: tre-admins/setup-instructions/prerequisites.md
      - 2. AD Tenant: tre-admins/setup-instructions/ad-tenant-choices.md
      - 3. Pre-deployment Steps: tre-admins/setup-instructions/pre-deployment-steps.md
      - 4. Deploying Azure TRE: tre-admins/setup-instructions/deploying-azure-tre.md
      - 5. Configuring Shared Services: tre-admins/setup-instructions/configuring-shared-services.md
      - 6. Installing Base Workspace: tre-admins/setup-instructions/installing-base-workspace.md
      - 7. Installing Workspace Service and User Resource: tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md

  - Using the Azure TRE: # Documentation for users of the TRE
      - Introduction: using-tre/index.md
      - Custom Templates: using-tre/templates/index.md
      # - Workspaces:
      #    - using-tre/wks/index.md # Documentation describing what a workspace is
      #    - Using Workspaces: using-tre/wks/using-wks.md # Interacting with workspaces (via the UI)
      #    - The Workspace Owner: using-tre/wks/wks-owner.md # Workspace Owners. The concept, and tasks
      # - FAQ: using-tre/faq.md # FAQ section (to allow easy contribution)

  - Templates and Services: # Docs to highlight and illustrate workspaces, workspace services etc
      - Workspaces:
          - Base: tre-templates/workspaces/base.md
          - Unrestricted: tre-templates/workspaces/unrestricted.md
      - Workspace Services:
          - Azure ML: tre-templates/workspace-services/azure-ml.md
          - Gitea: tre-templates/workspace-services/gitea.md
          - Guacamole: tre-templates/workspace-services/guacamole.md
          - InnerEye: tre-templates/workspace-services/inner-eye.md
          - MLFlow: tre-templates/workspace-services/mlflow.md
      - Shared Services:
          - Gitea (Source Mirror): tre-templates/shared-services/gitea.md
          - Nexus (Package Mirror): tre-templates/shared-services/nexus.md
          - Azure CycleCloud (HPC Compute): tre-templates/shared-services/cyclecloud.md
          - Airlock Notifier: tre-templates/shared-services/airlock-notifier.md
      - User Resources:
          - Guacamole Windows VM: tre-templates/user-resources/guacamole-windows-vm.md
          - Guacamole Linux VM: tre-templates/user-resources/guacamole-linux-vm.md

  - Technical Guide: # All Technical Documentation (Admin, Development)
      - Administration: # Docs related to the deployment and operation of AzureTRE infrastructure
          - Starting and Stopping Azure TRE Services: tre-admins/start-stop.md
          - Environment Variables: tre-admins/environment-variables.md
          - Tear-down: tre-admins/tear-down.md
          - Authentication and Authorization:
              - Introduction: tre-admins/auth.md
              - Manual Setup: tre-admins/identities/auth-manual.md
              - Identities:
                  - Application Admin: tre-admins/identities/application_admin.md
                  - API: tre-admins/identities/api.md
                  - Client: tre-admins/identities/client.md
                  - Automation Test Account: tre-admins/identities/test-account.md
                  - Workspaces: tre-admins/identities/workspace.md
          - Registring Templates: tre-admins/registering-templates.md

      - Development: # Docs related to the developing code for the AzureTRE
          - Local Development: using-tre/local-development/local-development.md
          - Contributing to AzureTRE: # Docs aimed at OSS developers, committing code to the AzureTRE repo
              - Introduction: tre-developers/index.md
              - API: tre-developers/api.md
              - UI: tre-developers/ui.md
              - Resource Processor: tre-developers/resource-processor.md
              - End to End Tests: tre-developers/end-to-end-tests.md
              - Letsencrypt: tre-developers/letsencrypt.md
              - Releases: tre-developers/release.md
              - GitHub Actions: tre-admins/setup-instructions/workflows.md

          - Developing Workspace Templates: # Docs aimed at developers creating workspace templates
              - Authoring Workspace Templates: tre-workspace-authors/authoring-workspace-templates.md
              - Firewall Rules: tre-workspace-authors/firewall-rules.md
              - Pipeline Templates:
                  - Overview: tre-templates/pipeline-templates/overview.md
                  - Pipeline Schema: tre-templates/pipeline-templates/pipeline-schema.md

      - Deploying the AzureTRE using CI/CD: using-tre/pipelines/pipelines.md

      - Troubleshooting FAQ: # General Troubleshooting Section for Development
          - troubleshooting-faq/index.md
          - Enabling Debugging for the API: troubleshooting-faq/debug-api.md
          - API logs using deployment center: troubleshooting-faq/api-logs-deployment-center.md
          - Checking the Service Bus: troubleshooting-faq/troubleshooting-sb.md
          - Checking Logs in Application Insights: troubleshooting-faq/app-insights-logs.md
          - Troubleshooting the Resource Processor: troubleshooting-faq/troubleshooting-rp.md
