---
apt:
  preserve_sources_list: false
  primary:
    - arches:
        - default
      uri: "${nexus_proxy_url}/repository/ubuntu/"

  security:
    - arches:
        - default
      uri: "${nexus_proxy_url}/repository/ubuntu-security/"
  sources_list: |
    deb [trusted=yes] $PRIMARY $RELEASE main restricted universe multiverse
    deb [trusted=yes] $PRIMARY $RELEASE-updates main restricted universe multiverse
    deb [trusted=yes] $SECURITY $RELEASE main restricted universe multiverse
    deb [trusted=yes] ${nexus_proxy_url}/repository/apt-pypi/ $RELEASE main restricted universe multiverse
    deb [signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] ${nexus_proxy_url}/repository/docker/ $RELEASE stable
