---
name: Deploy Azure TRE

on:
  schedule:
    # 1am each night https://crontab.guru/#0_1_*_*_*
    - cron: "0 1 * * *"
  push:
    branches: [main]
  # TODO: #478 fix for external contributions (forks)
  pull_request:
    types: [labeled]
    branches: [main]
  workflow_dispatch:

# This will prevent multiple runs of this entire workflow.
# We should NOT cancel in progress runs as that can destabilize the environment.
concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  run-deploy-tre-main:
    name: "Run deploy main"
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy_tre_reusable.yml
    secrets:
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACTIONS_ACR_NAME: ${{ secrets.ACTIONS_ACR_NAME }}
      ACTIONS_ACR_PASSWORD: ${{ secrets.ACTIONS_ACR_PASSWORD }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
      API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      CORE_ADDRESS_SPACE: ${{ secrets.CORE_ADDRESS_SPACE }}
      LOCATION: ${{ secrets.LOCATION }}
      MGMT_RESOURCE_GROUP: ${{ secrets.MGMT_RESOURCE_GROUP }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_STORAGE_ACCOUNT_NAME }}
      SWAGGER_UI_CLIENT_ID: ${{ secrets.SWAGGER_UI_CLIENT_ID }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_WORKSPACE_APP_ID: ${{ secrets.TEST_WORKSPACE_APP_ID }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TRE_ADDRESS_SPACE: ${{ secrets.TRE_ADDRESS_SPACE }}
      TRE_ID: ${{ secrets.TRE_ID }}

  prepare-not-main:
    name: Preparation
    runs-on: ubuntu-latest
    # The conditions below define the desired behaviour of the deployment
    # workflow:
    #   1. NOT for the main branch
    #   2. When a PR is labeled correctly
    #   3. The workflow run when pushed (update on PR branch) or
    #     manually triggered
    if: |
      github.ref != 'refs/heads/main' && (
      github.event_name == 'push'
      || github.event_name == 'workflow_dispatch'
      || contains(github.event.pull_request.labels.*.name, 'safe to test'))
    outputs:
      refid: ${{ steps.run-id.outputs.refid }}
    steps:
      - id: run-id
        name: Get run id
        run: |
          set -o errexit
          set -o pipefail
          set -o nounset

          REFID=$(echo ${GITHUB_REF} | shasum | cut -c1-8)
          echo "using id of: ${REFID} for GitHub Ref: ${GITHUB_REF}"
          echo "::set-output name=refid::${REFID}"

  run-deploy-tre-not-main:
    name: "Run deploy NOT main"
    if: github.ref != 'refs/heads/main'
    needs: [prepare-not-main]
    uses: ./.github/workflows/deploy_tre_reusable.yml
    secrets:
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      ACR_NAME: ${{ format('tre{0}', needs.prepare-not-main.outputs.refid) }}
      ACTIONS_ACR_NAME: ${{ secrets.ACTIONS_ACR_NAME }}
      ACTIONS_ACR_PASSWORD: ${{ secrets.ACTIONS_ACR_PASSWORD }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
      API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      CORE_ADDRESS_SPACE: ${{ secrets.CORE_ADDRESS_SPACE }}
      LOCATION: ${{ secrets.LOCATION }}
      MGMT_RESOURCE_GROUP: ${{ format('rg-tre{0}-mgmt', needs.prepare-not-main.outputs.refid) }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ format('tre{0}mgmt', needs.prepare-not-main.outputs.refid) }}
      SWAGGER_UI_CLIENT_ID: ${{ secrets.SWAGGER_UI_CLIENT_ID }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_WORKSPACE_APP_ID: ${{ secrets.TEST_WORKSPACE_APP_ID }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TRE_ADDRESS_SPACE: ${{ secrets.TRE_ADDRESS_SPACE }}
      TRE_ID: ${{ format('tre{0}', needs.prepare-not-main.outputs.refid) }}
