---
name: UI Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - "ui/app/**"
      - ".github/workflows/ui-tests.yml"
  push:
    branches: [main]
    paths:
      - "ui/app/**"

# for each ref (branch/pr) run just the most recent,
# cancel other pending/running ones
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run vitest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: ui/app
        run: yarn install

      - name: Copy config.source.json to config.json
        working-directory: ui/app/src
        run: cp config.source.json config.json

      - name: Run vitest
        working-directory: ui/app
        run: yarn test:coverage --run --reporter=junit --outputFile=junit.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-coverage-report
          path: ui/app/coverage
          retention-days: 10

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: ui/app/junit.xml
          retention-days: 10

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "ui/app/junit.xml"
          check_name: "UI Test Results"
          comment_mode: always
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}

      # For PR builds triggered from comment builds, the GITHUB_REF is set to main
      # so the checks aren't automatically associated with the PR
      # If prHeadSha is specified then explicity mark the checks for that SHA
      - name: Report check status
        if: github.event.workflow_run.head_sha != ''
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # the name must be identical to the one received by the real job
          sha: ${{ github.event.workflow_run.head_sha }}
          name: "UI Tests"
          status: "completed"
          conclusion: ${{ github.event.workflow_run.conclusion }}
          details_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
